apiVersion: v1
kind: Namespace
metadata:
  name: prod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
        image: saeed9124/ruby-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: http-server
  ports:
    - port: 80
      targetPort: 80
      
