name: Deploy to Production

on:
  push:
    branches:
      - prod  # Trigger the workflow on push to prod branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deploytoprod.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}

