name: Docker Build and Push

on:
  push:
    branches:
      - prod  # Set your branch name here

jobs:
  build-docker-and-push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: saeed9124/ruby-app:latest # Replace with your Docker Hub username and repository
